[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vtclear"
version = "1.0.3"
requires-python = ">=3.10"
authors = [
  { name = "Carlos A. Planchón", email = "carlosandresplanchonprestes@gmail.com" }
]
description = "Python ANSI VT100 implementation of Erase Screen."
readme = "README.md"
keywords = ["CLEAR", "VT100", "ANSI"]

license = "MIT"
license-files = ["LICENSE"]

classifiers = [
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Terminals",
  "Topic :: System :: Shells",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed"
]

[project.urls]
Repository = "https://github.com/carlosplanchon/vtclear.git"

[dependency-groups]
dev = ["pytest>=8", "mypy>=1.11"]

[tool.setuptools]
packages = ["vtclear"]

[tool.setuptools.package-data]
vtclear = ["py.typed"]

[tool.pytest.ini_options]
testpaths = ["tests"]
